version: 1
module_version: 0.0.2

test_defaults:
  before_init: ["terraform fmt -check"]

tests:
  - name: Default test
    environment:
      TF_VAR_aws_region: "eu-west-1"
      TF_VAR_bucket_name: "example-module-spacelift-ea2"